### ISSUE TITLE
Running `init.sh` in the root directory will prevent the priompt package from using the up-to-dated `tiktoken_node` lib

### ISSUE THREAD

**Issue by ghislaine-laios** [anysphere/priompt#16]
After running `init.sh` the `priompt` package cannot be built due to napi cannot find the up-to-dated `tiktoken_node` lib.

## Reproduce

```shell
./init.sh
cd priompt && pnpm build
```

## Rationale

`init.sh` would make the root dir to be the cargo workspace root, which would cause the `libanysphere_tiktoken_node.so` and `libanysphere_tiktoken_node.so` files to be built in the target folder of the root directory.

![image](https://github.com/user-attachments/assets/701fd04c-40a6-4c18-8f70-4153d51f6ecd)
![image](https://github.com/user-attachments/assets/5ec56741-7032-4d31-83a2-cfa0610f7cc9)

**Comment by arvid220u** [comment]
Thanks for reporting! I believe this is fixed now, but please re-open if you're still seeing this.
