### ISSUE TITLE
Yarn install error

### ISSUE THREAD

**Issue by trannhutle** [anysphere/priompt#18]
Hi team,

I am using `yarn` as my package manager. when i install the latest version, it required pnpm.

```
error @anysphere/tiktoken-node@0.2.0: The engine "yarn" is incompatible with this module. Expected version "please-use-pnpm". Got "1.22.0"
warning @anysphere/tiktoken-node@0.2.0: The engine "pnpm" appears to be invalid.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Can you please have a look at this. thank you.

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/c09c18e6-7c6e-45db-b538-4d4d3b789db8">

**Comment by arvid220u** [comment]
Thanks for reporting! I believe this is fixed now in 0.2.1.
