### ISSUE TITLE
Discovered small validation bug during recursive call

### ISSUE THREAD

**Issue by tg1482** [anysphere/priompt#6]
<img width="651" alt="Screenshot 2024-01-15 at 11 12 13 AM" src="https://github.com/anysphere/priompt/assets/31661606/dd1de846-0994-4939-b021-67f3f7a81574">

Discovered a small error which I think might be a bug. Happy to make a PR if you can grant me the right access.

**Comment by arvid220u** [comment]
Thank you! fixed here: https://github.com/anysphere/priompt/pull/8/commits/6c7a7fe5d2e1a9ffab9834abfbc30d8d63ad4f25
